SELECT BASE, COUNT(A.BASE) QNT

    FROM (SELECT 'CLC' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORACLC.USUARIO USU
          LEFT JOIN ORACLC.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'STR' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORASTR.USUARIO USU
          LEFT JOIN ORASTR.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'CSC' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORACSC.USUARIO USU
          LEFT JOIN ORACSC.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'OLT' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORAOLT.USUARIO USU
          LEFT JOIN ORAOLT.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'LMF' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORALMF.USUARIO USU
          LEFT JOIN ORALMF.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'PMD' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORAPMD.USUARIO USU
          LEFT JOIN ORAPMD.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'STG' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORASTG.USUARIO USU
          LEFT JOIN ORASTG.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'LMK' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORALMK.USUARIO USU
          LEFT JOIN ORALMK.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'PTK' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO        
          FROM ORAPTK.USUARIO USU
          LEFT JOIN ORAPTK.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO)
        
        UNION ALL
        
        SELECT 'PMI' BASE, USU.USU_NOME, USU.USU_CODIGO, USU_ATIVO, VEN.VEN_CODIGO
          FROM ORAPMI.USUARIO USU
          LEFT JOIN ORAPMI.VENDEDOR VEN
            ON (USU.VEN_CODIGO = VEN.VEN_CODIGO))A
WHERE A.USU_NOME = &NOME1
OR   A.USU_NOME = &NOME2
GROUP BY A.BASE
HAVING COUNT(A.BASE) < 1
